# AllCops:
#   Rails:
#     Eanbled: true
#   Include:
#     - '**/Gemfile'
#     - '**/Rakefile'
#   Exclude:
#     - 'bin/*'
#     - 'db/seeds.rb'
#     - 'db/schema.rb'
#     - 'vendor/bundle/**/*'
inherit_gem:
  rubocop-rails:
    - config/rails.yml

AllCops:
  TargetRubyVersion: 2.4.1
